Repository AY2425S1-CS2103T-W08-2/tp, pull requests merged in 2024-10, with the labels that each got.

#88 Add test cases for MarkPaidCommand
  src/main/java/seedu/address/logic/commands/MarkPaidCommand.java
  src/test/java/seedu/address/logic/commands/MarkPaidCommandTest.java
Labels: priority.Medium

#104 Add tutorial and participation classes
  src/main/java/seedu/address/model/Participation.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
Labels: priority.High

#130 Fix some style
  src/main/java/seedu/address/logic/parser/CreateTutorialCommandParser.java
  src/main/java/seedu/address/logic/parser/FindCommandParser.java
  src/main/java/seedu/address/logic/parser/ParserUtil.java
  src/main/java/seedu/address/logic/parser/PredicateFactory.java
  src/main/java/seedu/address/model/ModelManager.java
  src/main/java/seedu/address/model/predicate/StudentAttendedTutorialPredicate.java
  src/main/java/seedu/address/model/predicate/StudentHasPaidPredicate.java
Labels: type.Task

#200 Remove ParticipationList from Person Tutorial
  src/main/java/seedu/address/logic/Messages.java
  src/main/java/seedu/address/logic/commands/EditCommand.java
  src/main/java/seedu/address/logic/commands/MarkPaidCommand.java
  src/main/java/seedu/address/logic/parser/AddCommandParser.java
  src/main/java/seedu/address/model/participation/Participation.java
  src/main/java/seedu/address/model/person/Person.java
  src/main/java/seedu/address/model/tutorial/Tutorial.java
  src/main/java/seedu/address/model/util/SampleDataUtil.java
  src/main/java/seedu/address/storage/JsonAdaptedPerson.java
  src/test/java/seedu/address/model/person/PersonTest.java
  src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
  src/test/java/seedu/address/testutil/PersonBuilder.java
Labels: priority.Medium

#196 Remove filterp functions
  src/main/java/seedu/address/logic/commands/FilterPaidCommand.java
  src/main/java/seedu/address/logic/parser/AddressBookParser.java
  src/main/java/seedu/address/logic/parser/FilterPaidCommandParser.java
  src/test/java/seedu/address/logic/commands/FilterPaidCommandTest.java
  src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
  src/test/java/seedu/address/logic/parser/FilterPaidCommandParserTest.java
Labels: type.Task
